DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS insurance;

CREATE TABLE users (
id INTEGER PRIMARY KEY AUTOINCREMENT,
email TEXT UNIQUE NOT NULL,
password TEXT NOT NULL,
name TEXT NOT NULL,
surname TEXT NOT NULL,
tel INTEGER NOT NULL,
street_descriptive TEXT NOT NULL,
city TEXT NOT NULL,
zip_code INTEGER NOT NULL
);

CREATE TABLE insurance (
id INTEGER PRIMARY KEY AUTOINCREMENT,
insurance INTEGER NOT NULL,
amound INTEGER NOT NULL,
subject TEXT NOT NULL,
valid_from TEXT NOT NULL,
valid_until TEXT NOT NULL,
FOREIGN KEY (id) REFERENCES users (email)
);


--  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--  body TEXT NOT NULL,